name: First Workflow
on:
  [ workflow_dispatch,pull_request, push ]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.13
      options: --user root --cpus 2 --memory 2g
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run server
        run: uvicorn app:app --host 127.0.0.1 --port 8000 & sleep 3
      - name: Run tests
        run: pytest tests/tests.py --junitxml=reports/junit.xml
      - name: Archive reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path : reports/

        